### ISSUE TITLE
Coordinates do not locate any structure

### ISSUE THREAD

**Issue by Gamogamer** [xiazeqing/triwitch#2]
I generated from 1m to -1m. When running findtri afterwards, I get coords where there is nothing. Snow Biome, no structure in one instance.

I am not sure if I did the importing right. To me, it was unclear why you have the loop twice.

I will be grateful for all the help you can give me!

World is in 1.15, I used the 1.14 generator. In-game, I also checked with 1.14.4.
It was the same in both versions.

All my files can be found here: https://1drv.ms/u/s!AtsC9OpvpUwPhs5U7lVg5T-n0GK9dg?e=YJRBgw

I can provide them differently if that were to not work.

**Comment by 63815af756f0357940c666d2ae1c801d** [comment]
It seems that you have not gone to the right coordinate...
The coordinates in out.txt are CHUNK coordinates, which means they **must be 16x multiplied**.

For example, for your first line
-819310 -915936 -819305 -915945 -819296 -915935
which means In-game coordinates
-13108960,-14654976  -13108880,-14655120  -13108736,-14654960

And you can check them in https://www.chunkbase.com/apps/witch-hut-finder#-3346452860078228157


// P.S. Sorry for the long-time reply due to the network issue. It seems that the onedrive services are not available in Mainland China?
